server:
  port: 8082

spring:
  application:
    name: inventory-service

#  config:
#    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:h2:mem:inventorydb

  h2:
    console:
      enabled: true

    # Configuration JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  ## Configuration Eureka Client
  #eureka:
  #  client:
  #    service-url:
  #      defaultZone: http://localhost:8761/eureka/
  #    register-with-eureka: false